### ISSUE TITLE
Error "this.lastChild.setConfig is not a function" persists in 0.0.6 when mobile Chrome is used

### ISSUE THREAD

**Issue by Molodax** [custom-cards/group-card#16]
I am using the group-card as the following:

```
card:
  card:
    show_header_toggle: false
    title: Low Batteries
    type: entities
  entities:
    - group.all_batteries
  show_empty: false
  state_filter:
    - operator: <
      value: 20
  title: Low Batteries
  type: entity-filter
group: group.all_batteries
type: custom:group-card
```

It has fortunately started working after update to 0.0.6 in desktop version of Chrome, however, it doesn't work in mobile Chrome with the following error in the log:
`2021-06-14 11:57:50 ERROR (MainThread) [frontend.js.latest.202106030] https://xxx.xxx/hacsfiles/group-card/group-card.js:24:20 Uncaught TypeError: this.lastChild.setConfig is not a function`

I have cleared cash in the browser but it doesn't help.

**Comment by inhibitz** [comment]
confirmed
