### ISSUE TITLE
Is the group-card correctly working with 0.107.x?

### ISSUE THREAD

**Issue by Molodax** [custom-cards/group-card#8]
I've updated from 0.106.6 to 0.107.1 and now have multiple problems with lovelace, like lovelace dashboard is not loading, media cards are not available etc. I also use groupd-card  and have this in my logs:

Logger: frontend.js.latest.202003181
Source: components/system_log/__init__.py:209
First occurred: March 19, 2020, 6:47:49 PM (19 occurrences)
Last logged: 9:39:43 AM

https://mydomain.xxx/hacsfiles/group-card/group-card.js:24:20 Uncaught TypeError: this.lastChild.setConfig is not a function
https://mydomain.xxx/config/helpers:0:0 ResizeObserver loop limit exceeded
https://mydomain.xxx/frontend_latest/chunk.ea4a842548b68b236f48.js:1753:204645 Uncaught YAMLException: unacceptable kind of an object to dump [object Undefined]
https://mydomain.xxx/frontend_latest/chunk.ea4a842548b68b236f48.js:2559:2300 Uncaught TypeError: Cannot read property 'replaceChild' of null
https://mydomain.xxx/frontend_latest/chunk.ea4a842548b68b236f48.js:795:320 Uncaught TypeError: Cannot read property 'replaceChild' of null

**Comment by RonJ103** [comment]
I'm also having issues.  I'm on 0.107, but I don't know for sure when this started.

**Comment by eldirinice** [comment]
I'm also experiencing this issue, and it also started after upgrading to 0.107.x for me. Still experiencing it on 0.108.x. I've removed the card for now until this is addressed.

**Comment by Molodax** [comment]
It is a pity that such simple and a very useful card is broken, would it be possible that @ciotlosm or @iantrich could resolve the issue?
Log from the latest 0.110.1:

`2020-05-24 11:37:54 ERROR (MainThread) [frontend.js.latest.202005191] https://xxx.xxx/hacsfiles/group-card/group-card.js:24:20 Uncaught TypeError: this.lastChild.setConfig is not a function`
